name: Deploy to Firebase on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Substitute Firebase Config
        run: |
          sed -i "s|VITE_FIREBASE_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g" public/js/firebase.js
          sed -i "s|VITE_FIREBASE_AUTH_DOMAIN|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" public/js/firebase.js
          sed -i "s|VITE_FIREBASE_PROJECT_ID|${{ secrets.FIREBASE_PROJECT_ID }}|g" public/js/firebase.js
          sed -i "s|VITE_FIREBASE_STORAGE_BUCKET|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" public/js/firebase.js
          sed -i "s|VITE_FIREBASE_MESSAGING_SENDER_ID|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" public/js/firebase.js
          sed -i "s|VITE_FIREBASE_APP_ID|${{ secrets.FIREBASE_APP_ID }}|g" public/js/firebase.js
          sed -i "s|VITE_GCAL_API_KEY|${{ secrets.GCAL_API_KEY }}|g" public/js/firebase.js


      - name: Install Function Dependencies
        run: npm --prefix functions install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # New authentication step using the official Google action
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCHIKKO_RULES }}'

      # The deploy step no longer needs a token
      - name: Deploy to Firebase for Preview
        run: firebase deploy --only functions,hosting --project schikko-rules