name: Deploy to Firebase on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Substitute Firebase Config
        run: |
          sed -i "s|VITE_FIREBASE_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g" public/js/firebase.js
          sed -i "s|VITE_FIREBASE_AUTH_DOMAIN|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" public/js/firebase.js
          sed -i "s|VITE_FIREBASE_PROJECT_ID|${{ secrets.FIREBASE_PROJECT_ID }}|g" public/js/firebase.js
          sed -i "s|VITE_FIREBASE_STORAGE_BUCKET|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" public/js/firebase.js
          sed -i "s|VITE_FIREBASE_MESSAGING_SENDER_ID|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" public/js/firebase.js
          sed -i "s|VITE_FIREBASE_APP_ID|${{ secrets.FIREBASE_APP_ID }}|g" public/js/firebase.js
      
      - name: Install Function Dependencies
        run: npm --prefix functions install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only functions,hosting --project schikko-rules --token ${{ secrets.FIREBASE_TOKEN }}